// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobRun = `-- name: GetJobRun :one
SELECT id, job_name, biz_date, status, started_at, finished_at, error_code, error_message, retry_count, progress_current, progress_total, meta, created_at
FROM job_run_log
WHERE id = $1
`

func (q *Queries) GetJobRun(ctx context.Context, id int64) (JobRunLog, error) {
	row := q.db.QueryRow(ctx, getJobRun, id)
	var i JobRunLog
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.BizDate,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT id, job_name, biz_date, status, started_at, finished_at, error_code, error_message, retry_count, progress_current, progress_total, meta, created_at
FROM job_run_log
WHERE ($1::text = '' OR job_name = $1)
  AND ($2::date IS NULL OR biz_date = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListJobRunsParams struct {
	Column1 string
	Column2 pgtype.Date
	Limit   int32
	Offset  int32
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]JobRunLog, error) {
	rows, err := q.db.Query(ctx, listJobRuns,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRunLog
	for rows.Next() {
		var i JobRunLog
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.BizDate,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
