// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type JobRunLog struct {
	ID              int64
	JobName         string
	BizDate         pgtype.Date
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorCode       int32
	ErrorMessage    string
	RetryCount      int32
	ProgressCurrent int32
	ProgressTotal   int32
	Meta            []byte
	CreatedAt       pgtype.Timestamptz
}

type StockBasic struct {
	TsCode          string
	Symbol          string
	Name            string
	Area            pgtype.Text
	Industry        pgtype.Text
	Market          pgtype.Text
	Exchange        string
	ListDate        pgtype.Date
	DelistDate      pgtype.Date
	IsActive        bool
	Source          string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type StockDaily struct {
	TsCode          string
	TradeDate       pgtype.Date
	Open            pgtype.Numeric
	High            pgtype.Numeric
	Low             pgtype.Numeric
	Close           pgtype.Numeric
	PreClose        pgtype.Numeric
	Change          pgtype.Numeric
	PctChg          pgtype.Numeric
	Vol             pgtype.Numeric
	Amount          pgtype.Numeric
	Source          string
	DataStatus      string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UserPosition struct {
	ID           int64
	UserID       int64
	TsCode       string
	PositionDate pgtype.Date
	Quantity     pgtype.Numeric
	CostPrice    pgtype.Numeric
	Note         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WatchlistGroup struct {
	ID        int64
	UserID    int64
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WatchlistItem struct {
	ID        int64
	GroupID   int64
	TsCode    string
	Note      string
	CreatedAt pgtype.Timestamptz
}
