// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JobRunLog struct {
	ID              int64
	JobName         string
	BizDate         pgtype.Date
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	ErrorCode       int32
	ErrorMessage    string
	RetryCount      int32
	ProgressCurrent int32
	ProgressTotal   int32
	Meta            []byte
	CreatedAt       pgtype.Timestamptz
}

type StockBasic struct {
	TsCode          string
	Symbol          string
	Name            string
	Area            pgtype.Text
	Industry        pgtype.Text
	Market          pgtype.Text
	Exchange        string
	ListDate        pgtype.Date
	DelistDate      pgtype.Date
	IsActive        bool
	Source          string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type StockDaily struct {
	TsCode          string
	TradeDate       pgtype.Date
	Open            pgtype.Numeric
	High            pgtype.Numeric
	Low             pgtype.Numeric
	Close           pgtype.Numeric
	PreClose        pgtype.Numeric
	Change          pgtype.Numeric
	PctChg          pgtype.Numeric
	Vol             pgtype.Numeric
	Amount          pgtype.Numeric
	Source          string
	DataStatus      string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
