// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPosition = `-- name: CreateUserPosition :one
INSERT INTO user_position (
    user_id,
    ts_code,
    position_date,
    quantity,
    cost_price,
    note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, ts_code, position_date, quantity, cost_price, note, created_at, updated_at
`

type CreateUserPositionParams struct {
	UserID       int64
	TsCode       string
	PositionDate pgtype.Date
	Quantity     pgtype.Numeric
	CostPrice    pgtype.Numeric
	Note         string
}

func (q *Queries) CreateUserPosition(ctx context.Context, arg CreateUserPositionParams) (UserPosition, error) {
	row := q.db.QueryRow(ctx, createUserPosition,
		arg.UserID,
		arg.TsCode,
		arg.PositionDate,
		arg.Quantity,
		arg.CostPrice,
		arg.Note,
	)
	var i UserPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TsCode,
		&i.PositionDate,
		&i.Quantity,
		&i.CostPrice,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPosition = `-- name: DeleteUserPosition :execrows
DELETE FROM user_position
WHERE id = $1 AND user_id = $2
`

type DeleteUserPositionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteUserPosition(ctx context.Context, arg DeleteUserPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPosition, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserPositions = `-- name: ListUserPositions :many
SELECT id, user_id, ts_code, position_date, quantity, cost_price, note, created_at, updated_at
FROM user_position
WHERE user_id = $1
ORDER BY position_date DESC, id DESC
`

func (q *Queries) ListUserPositions(ctx context.Context, userID int64) ([]UserPosition, error) {
	rows, err := q.db.Query(ctx, listUserPositions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPosition
	for rows.Next() {
		var i UserPosition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TsCode,
			&i.PositionDate,
			&i.Quantity,
			&i.CostPrice,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPosition = `-- name: UpdateUserPosition :one
UPDATE user_position
SET ts_code = $3,
    position_date = $4,
    quantity = $5,
    cost_price = $6,
    note = $7,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, ts_code, position_date, quantity, cost_price, note, created_at, updated_at
`

type UpdateUserPositionParams struct {
	ID           int64
	UserID       int64
	TsCode       string
	PositionDate pgtype.Date
	Quantity     pgtype.Numeric
	CostPrice    pgtype.Numeric
	Note         string
}

func (q *Queries) UpdateUserPosition(ctx context.Context, arg UpdateUserPositionParams) (UserPosition, error) {
	row := q.db.QueryRow(ctx, updateUserPosition,
		arg.ID,
		arg.UserID,
		arg.TsCode,
		arg.PositionDate,
		arg.Quantity,
		arg.CostPrice,
		arg.Note,
	)
	var i UserPosition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TsCode,
		&i.PositionDate,
		&i.Quantity,
		&i.CostPrice,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
