// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStock = `-- name: GetStock :one
SELECT ts_code, symbol, name, area, industry, market, exchange, list_date, delist_date, is_active, source, updated_at
FROM stock_basic
WHERE ts_code = $1
`

type GetStockRow struct {
	TsCode     string
	Symbol     string
	Name       string
	Area       pgtype.Text
	Industry   pgtype.Text
	Market     pgtype.Text
	Exchange   string
	ListDate   pgtype.Date
	DelistDate pgtype.Date
	IsActive   bool
	Source     string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetStock(ctx context.Context, tsCode string) (GetStockRow, error) {
	row := q.db.QueryRow(ctx, getStock, tsCode)
	var i GetStockRow
	err := row.Scan(
		&i.TsCode,
		&i.Symbol,
		&i.Name,
		&i.Area,
		&i.Industry,
		&i.Market,
		&i.Exchange,
		&i.ListDate,
		&i.DelistDate,
		&i.IsActive,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listStockDaily = `-- name: ListStockDaily :many
SELECT ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount, source, data_status
FROM stock_daily
WHERE ts_code = $1 AND trade_date BETWEEN $2 AND $3
ORDER BY trade_date
`

type ListStockDailyParams struct {
	TsCode      string
	TradeDate   pgtype.Date
	TradeDate_2 pgtype.Date
}

type ListStockDailyRow struct {
	TsCode     string
	TradeDate  pgtype.Date
	Open       pgtype.Numeric
	High       pgtype.Numeric
	Low        pgtype.Numeric
	Close      pgtype.Numeric
	PreClose   pgtype.Numeric
	Change     pgtype.Numeric
	PctChg     pgtype.Numeric
	Vol        pgtype.Numeric
	Amount     pgtype.Numeric
	Source     string
	DataStatus string
}

func (q *Queries) ListStockDaily(ctx context.Context, arg ListStockDailyParams) ([]ListStockDailyRow, error) {
	rows, err := q.db.Query(ctx, listStockDaily, arg.TsCode, arg.TradeDate, arg.TradeDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockDailyRow
	for rows.Next() {
		var i ListStockDailyRow
		if err := rows.Scan(
			&i.TsCode,
			&i.TradeDate,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.PreClose,
			&i.Change,
			&i.PctChg,
			&i.Vol,
			&i.Amount,
			&i.Source,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocks = `-- name: ListStocks :many
SELECT ts_code, symbol, name, area, industry, market, exchange, list_date, delist_date, is_active, source, updated_at
FROM stock_basic
WHERE ($1::text = '' OR ts_code ILIKE '%' || $1 || '%' OR symbol ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY ts_code
LIMIT $2 OFFSET $3
`

type ListStocksParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListStocksRow struct {
	TsCode     string
	Symbol     string
	Name       string
	Area       pgtype.Text
	Industry   pgtype.Text
	Market     pgtype.Text
	Exchange   string
	ListDate   pgtype.Date
	DelistDate pgtype.Date
	IsActive   bool
	Source     string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListStocks(ctx context.Context, arg ListStocksParams) ([]ListStocksRow, error) {
	rows, err := q.db.Query(ctx, listStocks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStocksRow
	for rows.Next() {
		var i ListStocksRow
		if err := rows.Scan(
			&i.TsCode,
			&i.Symbol,
			&i.Name,
			&i.Area,
			&i.Industry,
			&i.Market,
			&i.Exchange,
			&i.ListDate,
			&i.DelistDate,
			&i.IsActive,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
