// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (
    username,
    display_name,
    password_hash,
    status,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, username, display_name, password_hash, status, role, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.Role,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, status, role, last_login_at, created_at, updated_at
FROM app_user
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, status, role, last_login_at, created_at, updated_at
FROM app_user
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE app_user
SET last_login_at = $2,
    updated_at = now()
WHERE id = $1
`

type TouchUserLastLoginParams struct {
	ID          int64
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) TouchUserLastLogin(ctx context.Context, arg TouchUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const updateBootstrapUser = `-- name: UpdateBootstrapUser :one
UPDATE app_user
SET display_name = $2,
    password_hash = $3,
    status = $4,
    role = $5,
    updated_at = now()
WHERE username = $1
RETURNING id, username, display_name, password_hash, status, role, last_login_at, created_at, updated_at
`

type UpdateBootstrapUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	Status       string
	Role         string
}

func (q *Queries) UpdateBootstrapUser(ctx context.Context, arg UpdateBootstrapUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateBootstrapUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.Role,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
