// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlists.sql

package dbgen

import (
	"context"
)

const createWatchlistGroup = `-- name: CreateWatchlistGroup :one
INSERT INTO watchlist_group (
    user_id,
    name,
    sort_order
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, name, sort_order, created_at, updated_at
`

type CreateWatchlistGroupParams struct {
	UserID    int64
	Name      string
	SortOrder int32
}

func (q *Queries) CreateWatchlistGroup(ctx context.Context, arg CreateWatchlistGroupParams) (WatchlistGroup, error) {
	row := q.db.QueryRow(ctx, createWatchlistGroup, arg.UserID, arg.Name, arg.SortOrder)
	var i WatchlistGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWatchlistItem = `-- name: CreateWatchlistItem :one
INSERT INTO watchlist_item (
    group_id,
    ts_code,
    note
)
SELECT g.id, $2, $3
FROM watchlist_group AS g
WHERE g.id = $1 AND g.user_id = $4
RETURNING id, group_id, ts_code, note, created_at
`

type CreateWatchlistItemParams struct {
	ID     int64
	TsCode string
	Note   string
	UserID int64
}

func (q *Queries) CreateWatchlistItem(ctx context.Context, arg CreateWatchlistItemParams) (WatchlistItem, error) {
	row := q.db.QueryRow(ctx, createWatchlistItem,
		arg.ID,
		arg.TsCode,
		arg.Note,
		arg.UserID,
	)
	var i WatchlistItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TsCode,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWatchlistGroup = `-- name: DeleteWatchlistGroup :execrows
DELETE FROM watchlist_group
WHERE id = $1 AND user_id = $2
`

type DeleteWatchlistGroupParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteWatchlistGroup(ctx context.Context, arg DeleteWatchlistGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWatchlistGroup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWatchlistItem = `-- name: DeleteWatchlistItem :execrows
DELETE FROM watchlist_item AS i
USING watchlist_group AS g
WHERE i.id = $1
  AND i.group_id = $2
  AND g.id = i.group_id
  AND g.user_id = $3
`

type DeleteWatchlistItemParams struct {
	ID      int64
	GroupID int64
	UserID  int64
}

func (q *Queries) DeleteWatchlistItem(ctx context.Context, arg DeleteWatchlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWatchlistItem, arg.ID, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWatchlistGroup = `-- name: GetWatchlistGroup :one
SELECT id, user_id, name, sort_order, created_at, updated_at
FROM watchlist_group
WHERE id = $1 AND user_id = $2
`

type GetWatchlistGroupParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetWatchlistGroup(ctx context.Context, arg GetWatchlistGroupParams) (WatchlistGroup, error) {
	row := q.db.QueryRow(ctx, getWatchlistGroup, arg.ID, arg.UserID)
	var i WatchlistGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWatchlistGroups = `-- name: ListWatchlistGroups :many
SELECT id, user_id, name, sort_order, created_at, updated_at
FROM watchlist_group
WHERE user_id = $1
ORDER BY sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListWatchlistGroups(ctx context.Context, userID int64) ([]WatchlistGroup, error) {
	rows, err := q.db.Query(ctx, listWatchlistGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchlistGroup
	for rows.Next() {
		var i WatchlistGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistItems = `-- name: ListWatchlistItems :many
SELECT i.id, i.group_id, i.ts_code, i.note, i.created_at
FROM watchlist_item AS i
INNER JOIN watchlist_group AS g ON g.id = i.group_id
WHERE i.group_id = $1 AND g.user_id = $2
ORDER BY i.created_at ASC, i.id ASC
`

type ListWatchlistItemsParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) ListWatchlistItems(ctx context.Context, arg ListWatchlistItemsParams) ([]WatchlistItem, error) {
	rows, err := q.db.Query(ctx, listWatchlistItems, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchlistItem
	for rows.Next() {
		var i WatchlistItem
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TsCode,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchlistGroup = `-- name: UpdateWatchlistGroup :one
UPDATE watchlist_group
SET name = $3,
    sort_order = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, sort_order, created_at, updated_at
`

type UpdateWatchlistGroupParams struct {
	ID        int64
	UserID    int64
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateWatchlistGroup(ctx context.Context, arg UpdateWatchlistGroupParams) (WatchlistGroup, error) {
	row := q.db.QueryRow(ctx, updateWatchlistGroup,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.SortOrder,
	)
	var i WatchlistGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
